name: 💄 CI Frontend

on:
  pull_request:
  workflow_dispatch:

jobs:
  # waiting for status check to play well with path filters
  # https://github.community/t/status-check-with-path-filter/18049/2
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths: '["client/**"]'
          do_not_skip: '["workflow_dispatch", "schedule"]'

  eslint:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'client'
      - name: lint with reporting
        run: |
          npm install
          npm lint:report
        continue-on-error: true
      #      - name: Annotate Code Linting Results
      #        uses: ataylorme/eslint-annotate-action@1.2.0
      #        with:
      #          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      #          report-json: "client/eslint_report.json"
      - name: Upload ESLint report
        uses: actions/upload-artifact@v2
        with:
          name: eslint_report.json
          path: client/eslint_report.json
  compile:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'client'
      - run: npm install
      - run: npm type-check
